services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flagman
      - TZ=Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - general
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  fastapi:
    build: .
    container_name: fastapi
    environment:
      - SECRET_KEY=c930fcdc49a10a69bfd11b1212c4146a493fef9868c8d0cf67d29bf465dcbf53
      - SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://postgres:123456@postgres/flagman
      - SQLALCHEMY_DATABASE_SYNC_URL=postgresql+psycopg://postgres:123456@postgres/flagman
      - WORKERS=2
      - HOST=0.0.0.0
    ports:
      - "0.0.0.0:8082:8082"
    volumes:
      - logs:/backend/logs
    depends_on:
      - postgres
    networks:
      - general


volumes:
  postgres_data:
  redis_data:
  es_data:
  logs:
  promtail_positions:

networks:
  general:
    external: true


