"""enterprise

Revision ID: 612ec91e755b
Revises: c48cf853e749
Create Date: 2025-04-12 11:28:34.210304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612ec91e755b'
down_revision: Union[str, None] = 'c48cf853e749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('boss_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'department', 'employee', ['boss_id'], ['employee_id'])
    op.add_column('enterprise', sa.Column('boss_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'enterprise', 'employee', ['boss_id'], ['employee_id'])
    op.drop_column('enterprise', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'enterprise', type_='foreignkey')
    op.drop_column('enterprise', 'boss_id')
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'boss_id')
    # ### end Alembic commands ###
