"""init2

Revision ID: c48cf853e749
Revises: 7c235ee554d9
Create Date: 2025-04-11 23:22:51.932462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48cf853e749'
down_revision: Union[str, None] = '7c235ee554d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('enterprise',
    sa.Column('enterprise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('enterprise_id')
    )
    op.create_table('department',
    sa.Column('department_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.enterprise_id'], ),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('document',
    sa.Column('document_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('employee_enterprise',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.enterprise_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'enterprise_id')
    )
    op.create_table('document_recipient',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('document_id', 'recipient_id')
    )
    op.create_table('document_signature',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.Column('confirmation_method', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('document_id', 'employee_id')
    )
    op.create_table('employee_department',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'department_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_department')
    op.drop_table('document_signature')
    op.drop_table('document_recipient')
    op.drop_table('employee_enterprise')
    op.drop_table('document')
    op.drop_table('department')
    op.drop_table('enterprise')
    op.drop_table('employee')
    # ### end Alembic commands ###
