"""departament_boss

Revision ID: cd1e61a516bb
Revises: 56c59d592f5d
Create Date: 2025-04-13 05:47:29.867578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1e61a516bb'
down_revision: Union[str, None] = '56c59d592f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departaments', sa.Column('boss_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departaments', 'employees', ['boss_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departaments', type_='foreignkey')
    op.drop_column('departaments', 'boss_id')
    # ### end Alembic commands ###
